#!/usr/bin/env bash
# Script to show information about domain

dig_fun(){
	local domain=$1
	local sub=$2
	res="$(dig "${sub}.${domain}" | grep -A1 'ANSWER SECTION:' | tr '\n' ' ')"
	ip="$(echo "${res}" | awk '{print $8}')"
	rec="$(echo "${res}" | awk '{print $7}')"
	echo "The subdomain ${sub} is a ${rec} record and points to ${ip}"
}

show_info(){
	local domain=$1
	local sub=$2

	if [[ ${sub} ]]; then
		dig_fun "${domain}" "${sub}"
	else
		server=('www' 'lb-01' 'web-01' 'web-02')
		for item in "${server[@]}"; do
			dig_fun "${domain}" "${item}"
		done

	fi
}

show_info "$1" "$2"
