#!/usr/bin/env bash
# This script to fix server in (webstack_debug_01)
apt update -y
apt install nginx -y
service nginx start
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
